//AMPLITUDE REPORT TYPES
export const AMPLITUDE_REPORT_TYPE_FUNNEL="FUNNEL"
export const AMPLITUDE_REPORT_TYPE_SEGMENT="SEGMENT"
export const AMPLITUDE_REPORT_TYPE_SESSION="SESSION"
export const AMPLITUDE_REPORT_TYPE_SPECIFIC = "SPECIFIC";
export const AMPLITUDE_REPORT_TYPE_ALL = "ALL";

//DEFAULT EMAIL VALUES
export const FEEDBACK_EMAIL_RECIPIENTS="john_doe@gmail.com,adam.sandler@hotmail.com";
export const FEEDBACK_EMAIL_SENDER="app.analytics@gmail.com";
export const FEEDBACK_EMAIL_SUBJECT="Amplitude Beta - Feedback from";
export const FEEDBACK_EMAIL_ROW_1_HEADER="Cobrand Id";
export const FEEDBACK_EMAIL_ROW_2_HEADER="Cobrand Name";
export const FEEDBACK_EMAIL_ROW_3_HEADER="User Name";
export const FEEDBACK_EMAIL_ROW_4_HEADER="Feedback"

//REDIS KEYS
export const REDIS_BUCKET = 'CUSTOMER_DATA';
export const REDIS_CRON_WORKER_GET_CUSTOMER_STATUS_KEY = "CRON_WORKER_GET_CUSTOMER_STATUS";
export const REDIS_CRON_WORKER_GET_REPORT_STATUS_KEY  = "CRON_WORKER_GET_REPORT_STATUS";
export const REDIS_CRON_MASTER_STATUS_KEY = "CRON_MASTER_STATUS";
export const REDIS_CUSTOMER_KEY = "CUSTOMER"

//CRON
export const STATUS_SUCCESS = "SUCCESS"
export const STATUS_FAILED = "FAILED";
export const STATUS_STARTED = "STARTED";

//DATE
export const DATE_FORMAT_ISO = "YYYY-MM-DDTHH:MM:SSZ";
export const DATE_UNIT_SECONDS = "SECONDS";
export const DATE_UNIT_MINUTES = "MINUTES";
export const DATE_UNIT_HOURS = "HOURS"
export const DATE_UNIT_DAYS = "DAYS"


